In [1]:
#numpyをダウンロード　& 基本的な配列作り　
# np.asarray()
import numpy as np
arr = np.asarray([1,2,3])
arr


array([1, 2, 3])

In [8]:
#配列の種類の変え方
#〇〇.astype(np.〇〇)
import numpy as np
arr = np.asarray([1,2,3], dtype=np.int32)
aarr = arr.astype(np.float32)
arr


array([1, 2, 3], dtype=int32)

In [13]:
#多次元配列作り
#中身をしっかりもう一回[]でくくるのが大事くさい
import numpy as np
warr = np.asarray([[1,2,3],[4,5,6],[7,8,9]])
warr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#m行n列だと　(m,n)って返してくれる
# 〇〇.shape
import numpy as np
arr = np.asarray([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [28]:
#特別な配列の作り方

#全部0
zero = np.zeros((2,3))
zero

#全部1
one = np.ones((4,3))
one

#全部0~1
random = np.random.rand(4,2)
random

#正規分布
e = np.random.randn(5,3)
print(zero)
print("===============================================")
print(one)
print("===============================================")
print(random)
print("===============================================")
print(e)



[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.67217592 0.92070386]
 [0.45118109 0.46390246]
 [0.24140286 0.40732379]
 [0.01694784 0.29363906]]
[[ 1.77159817 -1.5488798  -1.18552868]
 [ 0.4901876   0.99603734 -0.23629133]
 [-2.74040752  0.51017393 -0.15324452]
 [-0.41357137 -0.13559589 -1.22725366]
 [ 1.2818876   0.26328075 -0.86023951]]


In [32]:
#   とにかくnumpy の特徴は　配列の計算がしやすいこと！！！！

#通常のリスト
a = [1,2,3]
b = [4,5,6]
c = a + b
print("通常の和:  "+str(c))

#numpyのリスト
A = np.asarray([1,2,3])
B = np.asarray([4,5,6])
C =  A + B
print("numpyの和:  "+str(C))

通常の和:  [1, 2, 3, 4, 5, 6]
numpyの和:  [5 7 9]


In [39]:
# スカラー倍、　スカラー和もそう！！

#通常のリスト
try:
    a = [[1,2,3], [4,5,6]]
    b = a * 2
    c = a + 2
    print("通常のスカラー倍:  "+ str(b))
    print("通常のスカラー和:  "+ str(c))
except:
    print("通常の場合は　error だぁ")
    
print("===============================================")
    
#numpyのリスト
try:
    a = np.asarray([[1,2,3], [4,5,6]])
    b = a * 2
    c = a + 2
    print("numpyのスカラー倍:  "+ str(b))
    print("numpyのスカラー和:  "+ str(c))
except:
    print("")

通常の場合は　error だぁ
numpyのスカラー倍:  [[ 2  4  6]
 [ 8 10 12]]
numpyのスカラー和:  [[3 4 5]
 [6 7 8]]


In [ ]:
#   numpy の配列同士は、、、？
a = np.asarray(
    
    [[1,2,3],[4,5,6])